name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t tkaushik959/my-app:latest .

    - name: Push Docker Image to DockerHub
      run: docker push tkaushik959/my-app:latest

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > NEWKEY.pem
        chmod 600 DOCKER_KEY.pem

    - name: Deploy to EC2 and Run Container
      run: |
        ssh -o StrictHostKeyChecking=no -i NEWKEY.pem ubuntu@ec2-3-80-205-245.compute-1.amazonaws.com << 'EOF'
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker pull tkaushik959/my-app:latest
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 80:80 tkaushik959/my-app:latest
        EOF

